[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://kaplumbaga-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
