services:
  - type: web
    name: kaplumbaga-api
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 4000
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
